version: '2'
services:
    blogserasa-app:
        image: blogserasa
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://blogserasa-postgresql:5432/blogSerasa
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    blogserasa-postgresql:
        extends:
            file: postgresql.yml
            service: blogserasa-postgresql
